import os
import requests
import random
from datetime import datetime
from groq import Groq

# 1. 환경 변수
webhook_url = os.environ.get("DISCORD_WEBHOOK_URL")
groq_key = os.environ.get("GROQ_API_KEY")

client_groq = Groq(api_key=groq_key)

# 2. 모델 자동 선택
def get_best_model():
    try:
        models = client_groq.models.list()
        available_models = [m.id for m in models.data]
        # Llama 3 계열 우선
        for m in available_models:
            if "llama-3.3" in m: return m
        for m in available_models:
            if "llama-3.1" in m: return m
        return "mixtral-8x7b-32768"
    except:
        return "mixtral-8x7b-32768"

# 3. 분석 대상
targets = [
    "⚽ EPL: Man City vs Liverpool",
    "🏀 NBA: Lakers vs Warriors",
    "⚾ MLB: Dodgers vs Yankees",
    "⚽ UCL: Real Madrid vs Bayern"
]
today_target = random.choice(targets)
date_str = datetime.now().strftime("%Y-%m-%d")

# 4. 분석 요청 (JSON 모드 제거 -> 일반 텍스트 모드)
def get_ai_analysis():
    model = get_best_model()
    print(f"🤖 선택된 모델: {model}") # 로그 확인용

    prompt = f"""
    분석 대상: {today_target} ({date_str})
    역할: 냉철한 스포츠 도박사 AI
    
    디스코드 알림용으로 다음 형식을 엄격히 지켜서 대답해:
    
    📊 **승률 예측**
    - 홈팀: OO%
    - 무승부: OO%
    - 원정팀: OO%
    
    🎯 **AI 추천 픽**
    - (승무패 또는 언더/오버 중 하나만 선택)
    
    💡 **핵심 코멘트**
    - (데이터 기반 1줄 요약)
    """
    
    try:
        response = client_groq.chat.completions.create(
            messages=[{"role": "user", "content": prompt}],
            model=model,
            # response_format 삭제! (이게 에러 원인이었음)
        )
        return response.choices[0].message.content
    except Exception as e:
        print(f"❌ Groq API 에러 상세: {e}") # 로그에 진짜 원인 출력
        return f"⚠️ 분석 실패: {str(e)}"

# 5. 디스코드 전송
def send_discord():
    analysis_result = get_ai_analysis()
    
    # 봇 메시지 꾸미기
    payload = {
        "username": "AI Sports Edge",
        "avatar_url": "https://cdn-icons-png.flaticon.com/512/4140/4140047.png",
        "embeds": [
            {
                "title": f"🔥 {today_target} 분석",
                "description": analysis_result,
                "color": 15158332, # 빨간색 (Red)
                "footer": {
                    "text": "Generated by Groq AI • 재미로만 보세요"
                }
            }
        ]
    }

    try:
        if webhook_url:
            requests.post(webhook_url, json=payload)
            print("✅ 디스코드 전송 완료")
        else:
            print("⚠️ 웹훅 URL 없음")
            print(analysis_result)
    except Exception as e:
        print(f"❌ 전송 실패: {e}")

if __name__ == "__main__":
    send_discord()
